dist: trusty

# Add Google Chrome to installation
addons:
  chrome: stable

language: php

sudo: false

matrix:
  include:
  - php: 7.1
  - php: 7.2

# Make sure Java 8 is installed
jdk: oraclejdk8

install:
- composer install
# Start PHP server in public directory so requests route correctly and supress output
- php -S 127.0.0.1:8000 -t public >/dev/null 2>&1 &
# Sleep to make sure PHP server has started
- sleep 3

script:
- composer test